### ISSUE TITLE
Business Name Autofill.

### ISSUE THREAD

**Issue by amit-k86** [OrderMail/blacklabel#23]
Acceptance Criteria:-
1. At the time of Sign Up of User, User is asked to enter the business name he is associated. Auto Fill feature to suggest & correct business name at time of sign up.
2. Also after User Activation, User has to Select or Create a new Business. For Select or Creation, Auto Fill feature to suggest & correct business name at time of sign up.
3. Auto Fill Feature to work after 3 Alphabets.

Point of Discussion: - Whether Auto Fill capabilities to work country specific or region specific.

Tasks:-
1. HTML Prototype
2. Review with Team
3. Integration within the code.

**Comment by vikasagarwal** [comment]
@amit-k86  The scope of this issue has been covered as part of other stories. The point of discussion written int he description can be discussed. I don't think we need this story, please mark appropriately or close the story as you see fit.
