### ISSUE TITLE
Refactor Business Registration UI

### ISSUE THREAD

**Issue by vikasagarwal** [OrderMail/blacklabel#28]
The business registration view page needs to be rewritten because it is using two side-by-side for displaying fields and input fields. This is causing the UI to be broken if there is anything dynamic that's added to one of these divs.

The resolution is to use Bootstrap grid classes. This will ensure the responsiveness as well as the stability of the UI while newer fields are being added.

**Comment by priyankshukla** [comment]
@vikasagarwal 
Is anything remaining there? Did you use the Bootstrap grid classes? If you did, I am will closing this call and raising a separate issue for any further change.

**Comment by vikasagarwal** [comment]
This page has been refactored already. So, from the refactoring perspective nothing is remaining

**Comment by priyankshukla** [comment]
Closing this call as biz registration ui has been re-factored already.
