### ISSUE TITLE
Failure when signing up without selecting a business.

### ISSUE THREAD

**Issue by vikasagarwal** [OrderMail/blacklabel#29]
"If a user tries to sign up without selecting a business, the code breaks and the person is not able to proceed. However, when we reverted the branch's code to the previous commit (Feb 24th), it started working fine on Amit's machine

**Comment by priyankshukla** [comment]
Just want to make sure-->
Are we sure that we reset the indexes of User document? As the requirement got changed and the business is no more mandatory field here.

**Comment by vikasagarwal** [comment]
Priyank, speak with Amit and get it checked. I suggested him yesterday to
have Teamviewer so that one of the devs could remote into his machine. Call
him and sort this out.

On Fri, Mar 20, 2015 at 8:32 AM, Priyank Shukla <notifications@github.com>
wrote:

> Just want to make sure-->
> Are we sure that we reset the indexes of User document? As the requirement
> got changed and the business is no more mandatory field here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OrderMail/blacklabel/issues/29#issuecomment-83868478>.
>



-- 
Best Cricket T20 Coverage on:
http://cricket-t20.com

**Comment by priyankshukla** [comment]
Spoke to Amit, and get the unwanted index (businessname) removed from Users document.
Note- That is mandatory step, which each one us has to do at our end (I already mentioned this before)

He is able to register user without selecting the businessname. The bug has fixed now.

**Comment by amit-k86** [comment]
@priyankshukla - Thanks for the help. Issue Sorted
